defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 6
num_episodes: 1
seed: 0
gamma: 0.98
save_log: false
replay_path: None

actions: &actions [0, 1, 2, 3, 4, 5]
env_name: &env_name "TinyEmpty-4x4-v0"

env:
  _target_: uncertain_worms.environments.minigrid.minigrid_env.MinigridEnvironment
  env_name: ${env_name}
  fully_obs: true
  
agent:
  _target_: uncertain_worms.policies.fully_obs_planning_agent.FullyObsPlanningAgent
  fully_obs: true
  actions: *actions
  
  planner:
    _target_: uncertain_worms.planners.FO_DAStar.FO_DAStar
    actions: *actions
    transition_model: 
      _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_hardcoded_transition_model_gen
    reward_model:
      _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_hardcoded_reward_model_gen