defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 40
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None


actions: &actions [0, 1, 2, 3, 4, 5, 6, 7]

env:
  _target_: uncertain_worms.environments.rocksample.rocksample_env.RockSampleEnv
  fully_obs: false


agent:
  _target_: uncertain_worms.policies.partially_obs_planning_agent.PartiallyObsPlanningAgent
  fully_obs: false
  actions: *actions
  max_attempts: 250000
  num_particles: 50

  empty_state:
    _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_empty_state_gen

  empty_observation:
    _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_empty_observation_gen

  planner:
    _target_: uncertain_worms.planners.PO_DAStar.PO_DAStar
    actions: *actions

    lambda_coeff: 0.1
    entropy_coeff: 0.0
    max_expansions: 20000
    num_rollouts: 1
    continue_search_on_goal: true

    empty_observation:
      _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_empty_observation_gen
    initial_model: 
      _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_initial_model_gen
    transition_model: 
      _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_transition_model_gen
    reward_model:
      _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_reward_model_gen
    observation_model:
      _target_: uncertain_worms.environments.rocksample.rocksample_env.rocksample_observation_model_gen