defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 60
# max_steps: 20
num_episodes: 1
seed: 0
gamma: 0.98
save_log: false
replay_path: None

graphnav: &graphnav "spot_room_graphnav"


actions: &actions [0, 1, 2, 3, 4, 5, 6]
env:
  _target_: uncertain_worms.environments.spot.spot_env.SpotEnvironment
  fully_obs: false
  real_spot: false
  graphnav: *graphnav

agent:
  _target_: uncertain_worms.policies.partially_obs_planning_agent.PartiallyObsPlanningAgent
  num_particles: 10
  max_attempts: 25000
  fully_obs: false
  actions: *actions

  empty_state:
    _target_: uncertain_worms.environments.spot.spot_env.spot_empty_state_gen
    graphnav: *graphnav

  empty_observation:
    _target_: uncertain_worms.environments.spot.spot_env.spot_empty_observation_gen

  planner:
    _target_: uncertain_worms.planners.PO_DAStar.PO_DAStar
    actions: *actions

    empty_observation:
      _target_: uncertain_worms.environments.spot.spot_env.spot_empty_observation_gen

    max_expansions: 1000
    entropy_coeff: 1.0
    lambda_coeff: 0.0
    
    transition_model: 
      _target_: uncertain_worms.environments.spot.spot_env.spot_hardcoded_transition_model_gen
    reward_model:
      _target_: uncertain_worms.environments.spot.spot_env.spot_hardcoded_reward_model_gen
    observation_model:
      _target_: uncertain_worms.environments.spot.spot_env.spot_hardcoded_observation_model_gen
    initial_model: 
      _target_: uncertain_worms.environments.spot.spot_env.spot_hardcoded_initial_model_gen