defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 100
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None
actions: &actions [0, 1, 2, 3, 4, 5]
env_name: &env_name "MiniGrid-Empty-5x5-v0"


env:
  _target_: uncertain_worms.environments.minigrid.minigrid_env.MinigridEnvironment
  env_name: ${env_name}
  fully_obs: true
agent:
  _target_: uncertain_worms.policies.fully_obs_planning_agent.LLM_TR_FullyObsPlanningAgent
  env_code_path: environments/minigrid
  fully_obs: true
  actions: *actions
  dataset_path: "environments/minigrid/trajectory_data/${env_name}.pkl"

  planner:
    _target_: uncertain_worms.planners.FO_DAStar.FO_DAStar
    actions: *actions
    transition_model: 
      _target_: uncertain_worms.structs.empty_transition_model_gen
    reward_model:
      _target_: uncertain_worms.structs.empty_reward_model_gen
