defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 10
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None

actions: &actions [0, 1, 2]

env:
  _target_: uncertain_worms.environments.tiger.tiger_env.TigerEnv
  fully_obs: false

agent:
  _target_: uncertain_worms.policies.direct_llm_po_agent.DirectLLMPartiallyObsPolicy
  env_code_path: environments/tiger
  fully_obs: false
  actions: *actions
  dataset_path: "environments/tiger/trajectory_data/tiger_data.pkl"