defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 10
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None
env_name: &env_name "CornerGoalRandom-Empty-10x10-v0"
actions: &actions [0, 1, 2, 3, 4, 5]

env:
  _target_: uncertain_worms.environments.minigrid.minigrid_env.MinigridEnvironment
  fully_obs: false
  env_name: ${env_name}

agent:
  _target_: uncertain_worms.policies.tabular_learners.Tabular_TROI_PartiallyObsPlanningAgent
  fully_obs: false
  actions: *actions
  dataset_path: "environments/minigrid/trajectory_data/${env_name}.pkl"
  empty_state:
    _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_state_gen
    env_name: ${env_name}

  empty_observation:
    _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_observation_gen

  max_attempts: 250000
  num_particles: 10
  planner:
    _target_: uncertain_worms.planners.PO_DAStar.PO_DAStar
    actions: *actions
    max_expansions: 1000

    empty_observation:
      _target_: uncertain_worms.environments.minigrid.minigrid_env.minigrid_empty_observation_gen

    transition_model: 
      _target_: uncertain_worms.structs.empty_transition_model_gen
    reward_model:
      _target_: uncertain_worms.structs.empty_reward_model_gen
    initial_model: 
      _target_: uncertain_worms.structs.empty_initial_model_gen
    observation_model:
      _target_: uncertain_worms.structs.empty_observation_model_gen